# Generated by Django 3.1.2 on 2020-10-25 19:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True)),
                ('released_on', models.DateField(db_index=True, default=datetime.date.today)),
                ('album_length', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, 'Unrated'), (1, 'Flop'), (2, 'Average'), (3, 'Superhit'), (4, 'Blockbuster')], db_index=True)),
                ('rating_sample_space', models.IntegerField()),
                ('name', models.TextField(db_index=True)),
                ('released_on', models.DateField(db_index=True, default=datetime.date.today)),
                ('song_length', models.TextField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='mutecloud.album')),
                ('genres', models.ManyToManyField(db_index=True, related_name='songs', to='mutecloud.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('albums', models.ManyToManyField(related_name='artists', to='mutecloud.Album')),
                ('songs', models.ManyToManyField(related_name='artists', to='mutecloud.Song')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(db_index=True, related_name='albums', to='mutecloud.Genre'),
        ),
    ]
