# Generated by Django 3.1.2 on 2020-10-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutecloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Flop'), (2, 'Average'), (3, 'Superhit'), (4, 'Blockbuster')], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='rating_sample_space',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Flop'), (2, 'Average'), (3, 'Superhit'), (4, 'Blockbuster')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='rating_sample_space',
            field=models.IntegerField(default=0),
        ),
    ]
