# Generated by Django 3.1.2 on 2020-10-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutecloud', '0002_auto_20201026_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='rating_sample_space',
            new_name='reviewers',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='rating_sample_space',
            new_name='reviewers',
        ),
    ]
