# Generated by Django 3.1.2 on 2020-10-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutecloud', '0003_auto_20201026_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(db_index=True, related_name='artists', to='mutecloud.Album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='songs',
            field=models.ManyToManyField(db_index=True, related_name='artists', to='mutecloud.Song'),
        ),
    ]
