# Generated by Django 3.1.2 on 2020-10-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutecloud', '0004_auto_20201026_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Flop'), (2, 'Fade'), (3, 'Average'), (4, 'Classic'), (5, 'All Time')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Flop'), (2, 'Fade'), (3, 'Average'), (4, 'Classic'), (5, 'All Time')], db_index=True, default=0),
        ),
    ]
