# Generated by Django 3.1.2 on 2020-10-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutecloud', '0005_auto_20201026_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(db_index=True, related_name='artists', to='mutecloud.Genre'),
        ),
    ]
