# Generated by Django 3.1.2 on 2020-10-26 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutecloud', '0007_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(db_index=True, related_name='playlists', to='mutecloud.Song'),
        ),
    ]
